<?php
include 'display_folder.php';

$baseDirectory = './content/';

// Check if a specific folder is requested
if (isset($_GET['folder'])) {
    $folderName = $_GET['folder'];
    $directory = $baseDirectory . $folderName;
    displayFolderContents($directory);
} else {
    // Display the root folder contents
    displayFolderContents($baseDirectory);
}
?>

<!DOCTYPE html>
<html>

<head>
    <title>Content Folder</title>
    <style><?php require("./index.css");?></style></head>

<body>
    <div id="file-list">
        <!-- Folder and file content generated by PHP -->
    </div>
    <script src="index.js"></script>
</body>

</html>